/**
 * evidence.ts — the EvidenceBundle returned to Biro at closure.
 *
 * The bundle is the return leg of the seam and the far end of the spliced audit
 * chain: its `auditSegment` opens with Biro's chain head (`genesisPrevHash`) and
 * ends at `headHash`, which Biro then embeds in its own closure record. That two
 * way embedding is what makes tampering with either side break a hash both
 * custodians hold.
 */

import { z } from "zod";
import {
  ulid,
  hashHex,
  isoDateTime,
  currencyCode,
  minorUnits,
  complianceProfile,
  nistFunction,
} from "./common.js";
import { stepEvidence } from "./events.js";

/** Verdict of a single compliance/evidence gate. */
export const GATE_VERDICTS = ["pass", "fail", "waived", "not_applicable"] as const;

export const gateResult = z.object({
  gateId: z.string().min(1),
  /** NIST CSF function this gate contributes to. */
  nistFunction,
  verdict: z.enum(GATE_VERDICTS),
  /** Content hash of the gate's evidence artifact, if any. */
  artifactHash: hashHex.optional(),
  /** Reference(s) to the Cerbos / PolicyEngine decision that produced the verdict. */
  policyDecisionId: z.string().min(1).optional(),
});
export type GateResult = z.infer<typeof gateResult>;

/** Attestation that the plan was executed under its declared compliance profile. */
export const complianceAttestation = z.object({
  framework: complianceProfile,
  gateResults: z.array(gateResult),
});
export type ComplianceAttestation = z.infer<typeof complianceAttestation>;

/** Reserved vs. committed spend, reconciled against the lease. */
export const costActuals = z.object({
  reservedMinorUnits: minorUnits,
  committedMinorUnits: minorUnits,
  currency: currencyCode,
});
export type CostActuals = z.infer<typeof costActuals>;

/** Revenue generated by deployed agents, broken down by agent and period. */
export const revenueActuals = z.object({
  agentId: z.string().min(1),
  periodStart: isoDateTime,
  periodEnd: isoDateTime,
  amountMinorUnits: minorUnits,
  currency: currencyCode,
  /** Source of the revenue: 'stripe', 'marketplace', 'direct', etc. */
  source: z.string().min(1),
});
export type RevenueActuals = z.infer<typeof revenueActuals>;

/** Attribution record linking a customer payment to a specific agent. */
export const customerAttribution = z.object({
  paymentId: z.string().min(1),
  customerId: z.string().min(1),
  agentId: z.string().min(1),
  amountMinorUnits: minorUnits,
  currency: currencyCode,
  attributedAt: isoDateTime,
});
export type CustomerAttribution = z.infer<typeof customerAttribution>;

/** Marketplace listing record — URL and status of an agent published to a marketplace. */
export const marketplaceListing = z.object({
  listingUrl: z.string().url(),
  marketplaceId: z.string().min(1),
  agentId: z.string().min(1),
  status: z.enum(["published", "pending", "rejected", "removed"]),
  listedAt: isoDateTime,
  updatedAt: isoDateTime.optional(),
});
export type MarketplaceListing = z.infer<typeof marketplaceListing>;

/** A single entry in the Workforce audit segment. */
export const auditEntry = z.object({
  seq: z.number().int().nonnegative(),
  ts: isoDateTime,
  kind: z.string().min(1),
  workOrderId: ulid,
  /** Hash of the previous entry, or the segment genesis for the first entry. */
  prevHash: hashHex,
  /** Content hash of this entry's payload. */
  payloadHash: hashHex,
  /** Hash of this entry (covers the fields above). Chains to the next prevHash. */
  entryHash: hashHex,
});
export type AuditEntry = z.infer<typeof auditEntry>;

/** The Workforce-owned segment of the spliced hash chain. */
export const auditSegment = z.object({
  /** Biro's chain head at splice time — the genesis this segment hangs from. */
  genesisPrevHash: hashHex,
  /** The segment head — the last entryHash, carried back for Biro to embed. */
  headHash: hashHex,
  entries: z.array(auditEntry),
});
export type AuditSegment = z.infer<typeof auditSegment>;

export const evidenceBundle = z.object({
  workOrderId: ulid,
  /** Hash of the plan that was executed — must equal the approved plan's hash. */
  planHash: hashHex,
  /** Per-step evidence for the whole run. */
  steps: z.array(stepEvidence),
  complianceAttestation,
  costActuals,
  /** Revenue actuals from deployed agents (optional — backward compatible). */
  revenueActuals: z.array(revenueActuals).optional(),
  /** Customer attribution records (optional — backward compatible). */
  customerAttribution: z.array(customerAttribution).optional(),
  /** Marketplace listing records (optional — backward compatible). */
  marketplaceListing: z.array(marketplaceListing).optional(),
  auditSegment,
  /** Detached signature over the bundle's canonical content (Workforce's key). */
  signature: z.string().min(1),
});
export type EvidenceBundle = z.infer<typeof evidenceBundle>;

/**
 * Parse and validate an unknown value as an EvidenceBundle.
 * Throws a ZodError if validation fails.
 */
export function parseEvidenceBundle(input: unknown): EvidenceBundle {
  return evidenceBundle.parse(input);
}

/**
 * Safely parse an unknown value as an EvidenceBundle using Zod's safeParse.
 */
export function safeParseEvidenceBundle(input: unknown): { success: boolean; data?: EvidenceBundle; error?: z.ZodError } {
  const result = evidenceBundle.safeParse(input);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}
